#!/usr/bin/env python3
"""
Lament Runtime Support
======================

This module provides runtime support for executing Lament bytecode.
It implements a stack-based virtual machine that executes the bytecode
generated by the Lament compiler.

The runtime includes:
- Stack-based bytecode interpreter
- Temporal variable support
- Timeline tracking
- Memory management
- Built-in functions

This allows compiled Lament programs to run independently.
"""

import sys
import time
from typing import Any, List, Dict, Optional
from dataclasses import dataclass, field


# ============================================================================
# TIMELINE VALUE (Temporal Variable Implementation)
# ============================================================================

@dataclass
class TimelineValue:
    """
    A value that tracks its complete history across time.

    Every variable in Lament is a timeline that remembers all
    previous values, creation time, and assignment count.
    """
    current: Any
    history: List[Any] = field(default_factory=list)
    born_timestamp: float = field(default_factory=time.time)

    @property
    def age(self) -> int:
        """Number of assignments (including initial)."""
        return len(self.history)

    @property
    def origin(self) -> Any:
        """First value ever assigned."""
        return self.history[0] if self.history else None

    def past(self, steps: int = 1) -> Any:
        """Get value from N steps ago."""
        if steps <= 0 or steps > len(self.history):
            return None
        return self.history[-(steps + 1)] if steps < len(self.history) else None

    def assign(self, value: Any):
        """Assign a new value, recording in history."""
        self.history.append(self.current)
        self.current = value


# ============================================================================
# STACK-BASED VIRTUAL MACHINE
# ============================================================================

class LamentRuntime:
    """
    Stack-based virtual machine for executing Lament bytecode.

    Architecture:
    - Operand stack for evaluation
    - Call stack for function calls
    - Variable store (timeline values)
    - Constant pool
    - Name pool
    """

    def __init__(self):
        self.stack = []  # Operand stack
        self.call_stack = []  # Return addresses and frames
        self.variables = {}  # Variable name -> TimelineValue
        self.constants = []  # Constant pool
        self.names = []  # Name pool
        self.instructions = []  # Bytecode instructions
        self.ip = 0  # Instruction pointer
        self.halted = False

    def execute(self, bytecode: Dict):
        """
        Execute a bytecode object.

        Args:
            bytecode: Dict with 'constants', 'names', 'instructions'
        """
        print("\n" + "="*60)
        print("LAMENT RUNTIME - EXECUTING BYTECODE")
        print("="*60)

        # Load bytecode
        self.constants = bytecode.get('constants', [])
        self.names = bytecode.get('names', [])
        self.instructions = bytecode.get('instructions', [])
        self.ip = 0
        self.halted = False

        print(f"Loaded {len(self.constants)} constants")
        print(f"Loaded {len(self.names)} names")
        print(f"Loaded {len(self.instructions)} instructions")
        print()

        # Execute instruction loop
        while not self.halted and self.ip < len(self.instructions):
            self.execute_instruction()

        print("\n" + "="*60)
        print("EXECUTION COMPLETE")
        print("="*60)

    def execute_instruction(self):
        """Execute a single bytecode instruction."""
        if self.ip >= len(self.instructions):
            self.halted = True
            return

        instr = self.instructions[self.ip]
        op = instr.get('op') if isinstance(instr, dict) else str(instr)
        arg = instr.get('arg') if isinstance(instr, dict) else None

        # Dispatch to instruction handler
        handler = getattr(self, f'op_{op}', None)
        if handler:
            handler(arg)
        else:
            print(f"⚠️  Unknown instruction: {op}")
            self.ip += 1

    # ------------------------------------------------------------------------
    # STACK OPERATIONS
    # ------------------------------------------------------------------------

    def push(self, value: Any):
        """Push value onto stack."""
        self.stack.append(value)

    def pop(self) -> Any:
        """Pop value from stack."""
        if not self.stack:
            raise RuntimeError("Stack underflow")
        return self.stack.pop()

    def peek(self) -> Any:
        """Peek at top of stack without popping."""
        if not self.stack:
            return None
        return self.stack[-1]

    # ------------------------------------------------------------------------
    # INSTRUCTION HANDLERS
    # ------------------------------------------------------------------------

    def op_LOAD_CONST(self, const_idx: int):
        """Load constant onto stack."""
        if const_idx is not None and const_idx < len(self.constants):
            self.push(self.constants[const_idx])
        self.ip += 1

    def op_LOAD_VAR(self, name_idx: int):
        """Load variable value onto stack."""
        if name_idx is not None and name_idx < len(self.names):
            var_name = self.names[name_idx]
            if var_name in self.variables:
                timeline = self.variables[var_name]
                self.push(timeline.current)
            else:
                self.push(None)  # Undefined variable
        self.ip += 1

    def op_STORE_VAR(self, name_idx: int):
        """Store top of stack to variable."""
        value = self.pop()
        if name_idx is not None and name_idx < len(self.names):
            var_name = self.names[name_idx]
            if var_name in self.variables:
                self.variables[var_name].assign(value)
            else:
                # Create new timeline variable
                timeline = TimelineValue(current=value)
                timeline.history.append(value)
                self.variables[var_name] = timeline
        self.ip += 1

    def op_BINARY_ADD(self, _):
        """Add two values."""
        right = self.pop()
        left = self.pop()
        result = left + right if left is not None and right is not None else None
        self.push(result)
        self.ip += 1

    def op_BINARY_SUB(self, _):
        """Subtract two values."""
        right = self.pop()
        left = self.pop()
        result = left - right if left is not None and right is not None else None
        self.push(result)
        self.ip += 1

    def op_BINARY_MUL(self, _):
        """Multiply two values."""
        right = self.pop()
        left = self.pop()
        result = left * right if left is not None and right is not None else None
        self.push(result)
        self.ip += 1

    def op_BINARY_DIV(self, _):
        """Divide two values."""
        right = self.pop()
        left = self.pop()
        if right == 0:
            raise RuntimeError("Division by zero")
        result = left / right if left is not None and right is not None else None
        self.push(result)
        self.ip += 1

    def op_BINARY_MOD(self, _):
        """Modulo two values."""
        right = self.pop()
        left = self.pop()
        result = left % right if left is not None and right is not None else None
        self.push(result)
        self.ip += 1

    def op_BINARY_POW(self, _):
        """Power (exponentiation) of two values."""
        right = self.pop()
        left = self.pop()
        result = left ** right if left is not None and right is not None else None
        self.push(result)
        self.ip += 1

    def op_COMPARE_EQ(self, _):
        """Compare equality."""
        right = self.pop()
        left = self.pop()
        self.push(left == right)
        self.ip += 1

    def op_COMPARE_NE(self, _):
        """Compare inequality."""
        right = self.pop()
        left = self.pop()
        self.push(left != right)
        self.ip += 1

    def op_COMPARE_LT(self, _):
        """Compare less than."""
        right = self.pop()
        left = self.pop()
        self.push(left < right if left is not None and right is not None else False)
        self.ip += 1

    def op_COMPARE_GT(self, _):
        """Compare greater than."""
        right = self.pop()
        left = self.pop()
        self.push(left > right if left is not None and right is not None else False)
        self.ip += 1

    def op_COMPARE_LE(self, _):
        """Compare less than or equal."""
        right = self.pop()
        left = self.pop()
        self.push(left <= right if left is not None and right is not None else False)
        self.ip += 1

    def op_COMPARE_GE(self, _):
        """Compare greater than or equal."""
        right = self.pop()
        left = self.pop()
        self.push(left >= right if left is not None and right is not None else False)
        self.ip += 1

    def op_UNARY_NEG(self, _):
        """Negate value."""
        value = self.pop()
        self.push(-value if value is not None else None)
        self.ip += 1

    def op_UNARY_NOT(self, _):
        """Logical not."""
        value = self.pop()
        self.push(not value)
        self.ip += 1

    def op_JUMP(self, target: int):
        """Unconditional jump."""
        self.ip = target

    def op_JUMP_IF_FALSE(self, target: int):
        """Jump if top of stack is false."""
        condition = self.pop()
        if not condition:
            self.ip = target
        else:
            self.ip += 1

    def op_PRINT(self, _):
        """Print top of stack (confess statement)."""
        value = self.pop()
        print(f"💬 {value}")
        time.sleep(0.3)  # Emotional pause
        self.ip += 1

    def op_CALL(self, num_args: int):
        """Call function with N arguments."""
        # Pop function and arguments
        func = self.pop()
        args = [self.pop() for _ in range(num_args or 0)]
        args.reverse()

        # For now, just push None (function calls not fully implemented)
        self.push(None)
        self.ip += 1

    def op_RETURN(self, _):
        """Return from function."""
        return_value = self.pop()
        if self.call_stack:
            return_addr = self.call_stack.pop()
            self.ip = return_addr
            self.push(return_value)
        else:
            self.halted = True

    def op_MAKE_LIST(self, num_elements: int):
        """Create list from top N stack items."""
        elements = [self.pop() for _ in range(num_elements or 0)]
        elements.reverse()
        self.push(elements)
        self.ip += 1

    def op_INDEX(self, _):
        """Index into list/dict."""
        index = self.pop()
        obj = self.pop()
        if isinstance(obj, (list, dict)):
            try:
                result = obj[index]
            except (KeyError, IndexError):
                result = None
        else:
            result = None
        self.push(result)
        self.ip += 1

    def op_TEMPORAL(self, temporal_type: str):
        """Access temporal property of variable."""
        var_name = self.pop()
        if var_name in self.variables:
            timeline = self.variables[var_name]
            if temporal_type == 'AT_PAST':
                self.push(timeline.past())
            elif temporal_type == 'AT_ORIGIN':
                self.push(timeline.origin)
            elif temporal_type == 'AT_AGE':
                self.push(timeline.age)
            elif temporal_type == 'AT_BORN':
                self.push(timeline.born_timestamp)
            else:
                self.push(None)
        else:
            self.push(None)
        self.ip += 1

    def op_HALT(self, _):
        """Halt execution."""
        self.halted = True


# ============================================================================
# BYTECODE UTILITIES
# ============================================================================

def load_bytecode(filepath: str) -> Dict:
    """Load bytecode from file."""
    import json
    with open(filepath, 'r') as f:
        return json.load(f)


def save_bytecode(bytecode: Dict, filepath: str):
    """Save bytecode to file."""
    import json
    with open(filepath, 'w') as f:
        json.dump(bytecode, f, indent=2)


# ============================================================================
# COMMAND-LINE INTERFACE
# ============================================================================

def main():
    """Execute a Lament bytecode file."""
    import argparse

    parser = argparse.ArgumentParser(
        description='Lament Bytecode Runtime',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument('bytecode', help='Bytecode file to execute (.lmnt)')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='Verbose execution trace')

    args = parser.parse_args()

    try:
        # Load bytecode
        print(f"📦 Loading bytecode: {args.bytecode}")
        bytecode = load_bytecode(args.bytecode)

        # Execute
        runtime = LamentRuntime()
        runtime.execute(bytecode)

    except FileNotFoundError:
        print(f"❌ Error: Bytecode file not found: {args.bytecode}")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Runtime error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()
