#!/usr/bin/env python3
"""Lament code formatter CLI."""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from tools.formatter import main

if __name__ == '__main__':
    sys.exit(main())
