#!/usr/bin/env python3
"""Lament test framework CLI - Bootstrap wrapper."""
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from bootstrap_tool import run_lament_tool

if __name__ == '__main__':
    sys.exit(run_lament_tool('test_framework.lament', sys.argv[1:]))
