#!/usr/bin/env python3
"""
Lament Project Scaffolder CLI
"""

import sys
import os

# Add tools directory to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from scaffolder import main

if __name__ == '__main__':
    main()
