#!/usr/bin/env python3
"""Lament documentation generator CLI."""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from tools.docgen import main

if __name__ == '__main__':
    sys.exit(main())
